### PR TITLE
feat: add bluefin wallpapers

### PR DESCRIPTION
**Pull request by tulilirockz**
This should make it possible to get rid of the bluefin wallpapers from the bluefin repo over to this and build it on a COPR. This lets us build those for CentOS Stream and related.

### CODE REVIEW

**Comment by tulilirockz** [comment]
https://copr.fedorainfracloud.org/coprs/tulilirockz/bluefin-wallpapers-test/build/8444657/
Here is a successful build

**Comment by tulilirockz** [comment]
image

**Comment by tulilirockz** [comment]
oh! the xe wallpapers are missing still!

**Comment by tulilirockz** [comment]
image
https://copr.fedorainfracloud.org/coprs/tulilirockz/bluefin-wallpapers-test/build/8444666/

**Review by castrojo — APPROVED** [review]

**Pull request merged**
